<?php

/**
 * @file
 * Contains orbit.module.
 */

declare(strict_types=1);

use joshtronic\LoremIpsum;

/**
 * Common footer function for Oyster admin pages.
 *
 * @param bool $string
 *   If TRUE, return a rendered string instead of a render array.
 */
function orbit_page_footer($string = FALSE) {
  $build['footer'] = [
    '#markup' => '<div class="orbit-footer gin-layer-wrapper"><img src="' . orbit_logo_svg_url() . '" alt="Oyster design logo" align="right" width="148" height="45" /></div>',
  ];
  $build['#attached']['library'][] = 'orbit/base';

  if ($string) {
    $build = \Drupal::service('renderer')->render($build);
  }
  return $build;
}

/**
 * Undocumented function.
 *
 * @return string
 */
function orbit_logo_svg_url(): string {
  $module_path = \Drupal::service('extension.list.module')
    ->getPath('orbit');
  return \Drupal::service('file_url_generator')
    ->generateString($module_path . '/assets/logo.svg');
}

/**
 * Implements hook_theme().
 *
 * Https://www.drupal.org/docs/theming-drupal/twig-in-drupal/create-custom-twig-templates-for-custom-module.
 */
function orbit_theme($existing, $type, $theme, $path): array {
  return [
    'field__node__field_additional_body_content' => [
      'render element' => 'elements',
      'base hook' => 'field',
    ],
    'field__node__field_post_body_content_page_sec' => [
      'render element' => 'elements',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Wrapper function to generate Lorem Ipsum content for other modules.
 *
 * @param string $type
 *   $type Type of Dummy content to return, words/paragraphs.
 * @param int $count
 *   $count Number of items to be returned.
 * @param string $wrapper
 *   $wrapper What should the returned items be wrapped in.
 *
 * @return string
 *   $out String of dummy LoremIpsum content.
 */
function orbit_generate_dummy_text(string $type = 'paragraphs', int $count = 3, string $wrapper = 'p'): string
{
  $out = '';
  $lipsum = new LoremIpsum();

  switch ($type) {
    case 'paragraphs':
      $out = $lipsum->$type($count, $wrapper);
      break;

    case 'words':
      $out = $lipsum->$type($count);
      break;
  }

  return $out;
}
